### ISSUE TITLE
使用egg init创建项目后运行npm run dev报错，你们代码执行命令报错

### ISSUE THREAD

**Issue by AnizGu** [eggjs/egg-bin#222]
创建的是typescript项目，发现运行npm run dev报错，json解析语法错误
看了你们代码，在拼接命令参数时使用了单引号包裹了json参数，而且**没有做转义处理**。
![image](https://user-images.githubusercontent.com/69628287/218908936-dc99e46f-8b82-46db-add5-bf7206b60ceb.png)
![image](https://user-images.githubusercontent.com/69628287/218908962-21eabc9f-8294-4654-ab7d-62167b8e3cd3.png)

**Comment by atian25** [comment]
https://github.com/eggjs/egg-bin/blob/master/src/cmd/dev.ts#L47

@fengmk2 最新重构的这里好像有问题

**Comment by fengmk2** [comment]
我先重现看看

**Comment by fengmk2** [comment]
@AnizGu 我使用 https://github.com/eggjs/egg-boilerplate-ts 脚手架没有复现，能否提供一下复现方式。

![image](https://user-images.githubusercontent.com/156269/218946644-9c5bc73b-d9a6-4410-936c-ef1b82735d23.png)

**Comment by AnizGu** [comment]
原来还有个新的脚手架呀，没发现呢，有官网吗？

**Comment by fengmk2** [comment]
@AnizGu 使用 https://learn.microsoft.com/en-us/windows/wsl/install wsl 来跑

**Comment by AnizGu** [comment]
@fengmk2 
脚手架https://github.com/eggjs/egg-boilerplate-ts
用了wsl去运行还是一样的错误
![image](https://user-images.githubusercontent.com/69628287/219078240-c1b5e6dc-bf7d-454b-8193-9805446c736d.png)

**Comment by atian25** [comment]
@AnizGu 你改下本地的 `D:\Developments\EggProjects\showcase\node_modules\egg-bin\scripts\start-cluster. js:4`

在前面加一句 `console.log(process.argv)` 看看输出了啥

**Comment by fengmk2** [comment]
看起来是参数解析在 windows 下有兼容性问题，我加一个 encode 来解决吧。

**Comment by atian25** [comment]
咦，这个库的 windows ci 啥时干掉了？

**Comment by fengmk2** [comment]
https://github.com/eggjs/egg-bin/pull/190 去年11月

**Comment by atian25** [comment]
没必要干掉吧，反正 GitHub Actions 不收费。

**Comment by fengmk2** [comment]
https://github.com/eggjs/egg-bin/pull/223 @AnizGu 重新安装依赖即可
