### ISSUE TITLE
6.x 版本egg dev没有集成ets

### ISSUE THREAD

**Issue by evan-lc** [eggjs/egg-bin#242]
如题，6.x版本运行egg dev无法识别declarations配置，不会运行ets生成typings。这个符合预期吗，在changelog里没看到相关信息

**Comment by fengmk2** [comment]
给一个可以复现的 repo？

**Comment by fengmk2** [comment]
https://github.com/eggjs/egg-bin/blob/master/scripts/postinstall.js#L40 在 npm install 阶段没有执行 postinstall 吗？

**Comment by evan-lc** [comment]
> https://github.com/eggjs/egg-bin/blob/master/scripts/postinstall.js#L40 在 npm install 阶段没有执行 postinstall 吗？

我不是很理解，是说在postinstall执行ets么，难道更新typings靠重新npm install吗，这不太合理吧，之前都是egg-bin dev的时候执行ets

**Comment by evan-lc** [comment]
在packag.json加上如下配置可以了
`
"egg": {
    "require": "./node_modules/egg-ts-helper/register.js"
  },
`
@fengmk2 这属于breaking change了吧

**Comment by fengmk2** [comment]
先记个 bug

**Comment by fengmk2** [comment]
https://github.com/eggjs/egg-boilerplate-ts/blob/master/boilerplate/_package.json 需要使用 ts 的脚手架，配置加上

```json
  "egg": {
    "typescript": true
  }
```

**Comment by 52atlidong** [comment]
> > https://github.com/eggjs/egg-bin/blob/master/scripts/postinstall.js#L40 在 npm install 阶段没有执行 postinstall 吗？
> 
> 我不是很理解，是说在postinstall执行ets么，难道更新typings靠重新npm install吗，这不太合理吧，之前都是egg-bin dev的时候执行ets
我也不理解

**Comment by evan-lc** [comment]
> https://github.com/eggjs/egg-boilerplate-ts/blob/master/boilerplate/_package.json 需要使用 ts 的脚手架，配置加上
> 
> ```json
>   "egg": {
>     "typescript": true
>   }
> ```
试了下这个模版，把typing删了再npm run dev并不会重新生成类型声明文件

**Comment by malingxin** [comment]
`{
  "name": "sequelize-project",
  "version": "1.0.0",
  "description": "",
  "private": true,
  "egg": {
    "declarations": true,
    "typescript": true
  },
  "dependencies": {
    "egg": "^3.17.5",
    "egg-scripts": "2",
    "egg-sequelize": "^6.0.0",
    "mysql2": "^3.6.5"
  },
  "devDependencies": {
    "egg-bin": "6",
    "egg-mock": "5",
    "eslint": "^8.55.0",
    "eslint-config-egg": "^13.0.0",
    "sequelize-cli": "^6.6.2"
  },
  "engines": {
    "node": ">=18.0.0"
  },
  "scripts": {
    "start": "egg-scripts start --daemon --title=egg-server-sequelize-project",
    "stop": "egg-scripts stop --title=egg-server-sequelize-project",
    "dev": "egg-bin dev",
    "test": "npm run lint -- --fix && npm run test:local",
    "test:local": "egg-bin test",
    "cov": "egg-bin cov",
    "lint": "eslint .",
    "ci": "npm run lint && npm run cov"
  },
  "repository": {
    "type": "git",
    "url": ""
  },
  "author": "",
  "license": "MIT"
}
`

试了下，可以了，

> https://github.com/eggjs/egg-boilerplate-ts/blob/master/boilerplate/_package.json 需要使用 ts 的脚手架，配置加上
> 
> ```json
>   "egg": {
>     "typescript": true
>   }
> ```

**Comment by malingxin** [comment]
> > https://github.com/eggjs/egg-boilerplate-ts/blob/master/boilerplate/_package.json 需要使用 ts 的脚手架，配置加上
> > ```json
> >   "egg": {
> >     "typescript": true
> >   }
> > ```
> 
> 试了下这个模版，把typing删了再npm run dev并不会重新生成类型声明文件

`  "egg": {
    "declarations": true,
    "typescript": true
  },`

**Comment by evan-lc** [comment]
> > > https://github.com/eggjs/egg-boilerplate-ts/blob/master/boilerplate/_package.json 需要使用 ts 的脚手架，配置加上
> > > ```json
> > >   "egg": {
> > >     "typescript": true
> > >   }
> > > ```
> > 
> > 
> > 试了下这个模版，把typing删了再npm run dev并不会重新生成类型声明文件
> 
> ` "egg": { "declarations": true, "typescript": true },`

一样的，6.x的egg-bin的我试了还是不行

**Comment by trylovetom** [comment]
> > > > https://github.com/eggjs/egg-boilerplate-ts/blob/master/boilerplate/_package.json 需要使用 ts 的脚手架，配置加上
> > > > ```json
> > > >   "egg": {
> > > >     "typescript": true
> > > >   }
> > > > ```
> > > 
> > > 
> > > 试了下这个模版，把typing删了再npm run dev并不会重新生成类型声明文件
> > 
> > 
> > ` "egg": { "declarations": true, "typescript": true },`
> 
> 一样的，6.x的egg-bin的我试了还是不行

same problem here.
