### ISSUE TITLE
egg从2.x升级到3.17.5后，npm run debug不显示DevTools 地址

### ISSUE THREAD

**Issue by bi-kai** [eggjs/egg-bin#245]
用到的模块版本，是不是egg-bin降级5.x能解决下述问题？
```
    "egg": "^3.17.5",
    "egg-cors": "^3.0.0",
    "egg-jwt": "^3.1.7",
    "egg-mongoose": "^4.0.1",
    "egg-multipart": "^3.3.0",
    "egg-redis": "^2.5.0",
    "egg-scripts": "^2.17.0",
    "egg-sequelize": "^6.0.0",
    "egg-session-redis": "^2.1.0",
    "egg-view-nunjucks": "^2.3.0",

    "egg-bin": "^6.5.2",
    "egg-ci": "^2.2.0",
    "egg-mock": "^5.10.9",
```

## 问题1
之前用egg 2.x版本是可以显示的，如官网截图一样：
![image](https://github.com/eggjs/egg-bin/assets/15070379/4d90ab22-daef-4290-a467-6d420ee6a5d0)

 但egg升级到3.17.5版本，其他egg模块升级最新版本后，npm run debug如下：
![image](https://github.com/eggjs/egg-bin/assets/15070379/052a82d5-b9be-4103-b68b-43aa0cb24971)

该如何显示出chrome-devtools地址呢？ws地址不能直接在浏览器新页签中打开，不方便使用。

## 问题2
升级egg 3.x之后，config.default.js中，指定端口的配置，npm run start生效，npm run dev、debug不生效，始终是7001，该如何调整？
```
  // 修改dev模式监听的端口，默认7001
  config.cluster = {
    listen: {
      path: '',
      port: 3003,
      hostname: '0.0.0.0'
    }
  };
```

**Comment by fengmk2** [comment]
请使用 vscode 的 debug 吧，其他方式我们不提供官方支持了 https://github.com/eggjs/egg-boilerplate-ts/blob/master/boilerplate/.vscode/launch.json
