### ISSUE TITLE
egg-bin 启动时未生成typings目录反馈

### ISSUE THREAD

**Issue by yn-zxj** [eggjs/egg-bin#246]
在^6.5.2版本时，egg-ts-helper插件未工作，启动时没有生成typings文件夹及其目录，进行版本降低(^5)，运行正常

**Comment by Xiaofufufu** [comment]
我也遇到这个问题了，我的是"egg": "^3.17.5", "egg-cors": "^3.0.0",  "egg-bin": "^6", 就生成不了typings目录，开发的时候没有办法自动跳转到函数方法，将egg-bin 版本降到 5就可以了

**Comment by bi-kai** [comment]
https://github.com/eggjs/egg-bin/issues/245
我这里反馈的2个问题，后来排查，也是egg-bin 6导致的，降级到5.x就好了，bug好久都没人理，感觉不维护了
