### ISSUE TITLE
egg-bin@6，默认端口覆盖了 config.default.js 中配置的端口

### ISSUE THREAD

**Issue by JarryChung** [eggjs/egg-bin#250]
# 问题描述

![img_v3_027i_493fd4d1-0b8a-4689-a7cb-631ef0d3f22g](https://github.com/eggjs/egg-bin/assets/35088591/bcc90a0b-4191-464f-9a6a-5c67f3916acf)
如上图，_egg-bin@4_、_egg-bin@5_ 中，当 detect 到的端口与 `defaultPort` 一致时，将不会赋值给 `argv.port`，导致 `argv.port` 为空，进而用了 _config.default.js_ 里面配置的 `port`。

![image](https://github.com/eggjs/egg-bin/assets/35088591/fd667373-4e45-4eaf-a4dd-60ad92d6363a)
如上图，在 _egg-bin@6_ 中，任何情况都会赋值 `this.port`，也就意味着不会使用到 _config.default.js_ 中配置的 `port`。

与 6 版本相比，4/5 看起来是 bug 逻辑，但表现上符合业务预期。6 是正常逻辑，但表现上不符合业务预期。

# 期望

1. 麻烦帮忙确认下上述理解是否正确；
2. 能否调整端口获取的优先级为：--port > config 文件 > EGG_BIN_DEFAULT_PORT > 7001；
3. 建议以何种方式管理生产环境、开发环境的 port，分开管理还是集中管理？业务上，在不同环境的 port 是一样的。

致谢！

**Comment by fengmk2** [comment]
@JarryChung 可以来个 pr 修复一下，恢复跟之前的版本逻辑一致

**Comment by JarryChung** [comment]
@fengmk2 我改成了[这个逻辑](https://github.com/eggjs/egg-bin/pull/251/files)，PR 中的详细内容还没写，可以的话麻烦先帮忙看下逻辑是否 OK，晚点空了我再补充下测试用例及详细说明

**Comment by JarryChung** [comment]
@fengmk2 已添加测试用例，已在文档中注明获取端口顺序，已补充 PR 说明

**Comment by fengmk2** [comment]
@JarryChung PR 很完善！今天会合并发布
